site_name: Lightstream
site_url: https://example.com
nav:
  - Home: index.md
  - Getting started:
      Requirements: getting_started/requirements.md
      Installation: getting_started/installation.md
  - Tutorials:
      Image processing: tutorials/dataloading.md
      Image classification: tutorials/classification.md

theme:
  features:
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
  logo: images/lightning_icon.png
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/DIAGNijmegen/lightstream
repo_name: diagnijmegen/lightstream


plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences