"""Neighborhood Attention Transformer models and NCHW building blocks."""

from lightstream.models.nat.nchw import (
    ConvDownsampler,
    NCHWConvDownsampler,
    NCHWConvTokenizer,
    NCHWNAT,
    NCHWNatMini,
    NCHWNatNano,
    NCHWNatPico,
    NCHWNatSmall,
    NCHWNatBase,
    NCHWNATBlock,
    NCHWNATLayer,
    PointwiseConvMlp,
    convert_nchw_nat_state_dict,
    convert_nhwc_nat_state_dict,
    copy_nhwc_nat_block_to_nchw,
    copy_nhwc_nat_model_to_nchw,
    copy_nhwc_nat_to_nchw,
    copy_nhwc_conv_tokenizer_to_nchw,
    linear_to_pointwise_conv,
    pointwise_conv_to_linear,
    nchw_nat_base,
    nchw_nat_mini,
    nchw_nat_nano,
    nchw_nat_pico,
    nchw_nat_small,
    nchw_nat_tiny,
)
from lightstream.models.nat.streaming import StreamingNAT

StreamingNat = StreamingNAT

__all__ = [
    "ConvDownsampler",
    "NCHWConvDownsampler",
    "NCHWConvTokenizer",
    "NCHWNAT",
    "NCHWNatMini",
    "NCHWNatNano",
    "NCHWNatPico",
    "NCHWNatSmall",
    "NCHWNatBase",
    "NCHWNATBlock",
    "NCHWNATLayer",
    "PointwiseConvMlp",
    "convert_nchw_nat_state_dict",
    "convert_nhwc_nat_state_dict",
    "copy_nhwc_nat_block_to_nchw",
    "copy_nhwc_nat_model_to_nchw",
    "copy_nhwc_nat_to_nchw",
    "copy_nhwc_conv_tokenizer_to_nchw",
    "linear_to_pointwise_conv",
    "pointwise_conv_to_linear",
    "nchw_nat_base",
    "nchw_nat_mini",
    "nchw_nat_nano",
    "nchw_nat_pico",
    "nchw_nat_small",
    "nchw_nat_tiny",
    "StreamingNAT",
    "StreamingNat",
]
